### ISSUE TITLE
Highlight from "Highlight matching parenthesis" is applied to normal text 

### ISSUE THREAD

**Issue by beakerandjake** [objecthub/swift-lisppad-ios#1]
Fantastic application, I love using it while I go through SICP. 

I noticed a potential bug with parenthesis highlighting where the highlight will continually be applied to all characters as they are typed. 

Steps to Reproduce:
1. Open the application
2. In REPL mode type the following characters: `())`
4. Delete the two `))` to be left with `(`
5. Begin typing:  `(+ 1 2`
6. Observe the highlighting normally applied to parenthesis gets applied to the typed text.
7. Add the closing `)` to be left with `(+ 1 2)`
8. Observe the highlighting applied to the text is removed and the starting `(` is highlighted like normal.

![trim E0E02E8F-5CB8-4389-8692-6A2495D3F64F](https://github.com/objecthub/swift-lisppad-ios/assets/1727349/c5330440-5fc0-4719-8822-c27de6097687)

- **LispPad Version**: 1.3.4
- **Phone**: Iphone 14 Pro Max
- **iOS version**: 17.1.2

**Comment by objecthub** [comment]
Jake, thanks for submitting this issue and finding a way how to reproduce it. I noticed this behavior a few times and couldn't find a way for reproducing it reliably. Was due to a race condition which I just fixed. Will close the bug when this becomes available in the next release. Thanks!

**Comment by objecthub** [comment]
Version 2.0 of LispPad Go fixes this problem.

**Comment by beakerandjake** [comment]
Awesome work!
