### ISSUE TITLE
Editor does not clear text after selecting New

### ISSUE THREAD

**Issue by bcg2718** [objecthub/swift-lisppad-ios#2]
## Expected Behavior
In the Editor, selecting New should clear all text to allow typing a new file.

## Actual Behavior
Previous text remains after selecting New. However, switching to Console and back to Editor does clear previous text.

## Steps to Reproduce the Problem

  1. Switch to Editor
  2. Enter some text
  3. Select Save… from menu bar and save file to either iCloud Drive or On My iPhone
  4. Once back in Editor, select New from menu bar
  5. Notice that previous text remains in Editor
  6. Switch to Console
  7. Switch back to Editor
  8. Notice that previous text has disappeared and Editor is now clear as originally expected

  
https://github.com/objecthub/swift-lisppad-ios/assets/68421539/1e0918ab-09f8-4e2e-b04a-d7c8aa871e1e

## Specifications

  - Version: 2.0
  - Platform: iOS 17.3

**Comment by objecthub** [comment]
Thanks for the bug report and the detailed description for reproducing the issue. This has been fixed with commit 
566685e.

**Comment by objecthub** [comment]
This has been fixed with release 2.0.1.
