### ISSUE TITLE
Opening file from Recents or Favorites

### ISSUE THREAD

**Issue by bcg2718** [objecthub/swift-lisppad-ios#3]
## Expected Behavior
Opening a file in Editor from Recent or Favorites should treat the file as a previously saved file rather than a brand-new file that needs to be manually saved again.

## Actual Behavior
The file from Recent or Favorites is treated like a new file where the Save or Discard dialogue box appears when trying to start a new file. If Discard is chosen, the text disappears and any attempt to reload the file still shows a blank Editor as if the file contents have been lost. Switching to the Console and back to the Editor suddenly reveals the file contents.

## Steps to Reproduce the Problem

  1. Switch to Editor
  2. Choose Open… from the menu bar and select a file from Recent or Favorites
  3. Choose New from the menu bar
  4. Notice the dialogue box that prompts you to Save or Discard, as if the previously opened file had never been saved before.
  5. Choose Discard
  6. Notice the Editor is now clear of text
  7. Open the file once again by any method, such as selecting from Recent Files in the menu bar
  8. Notice the Editor remains blank as if the file contents have been lost
  9. Switch to Console and back to Editor
  10. Notice the file contents have reappeared 

https://github.com/objecthub/swift-lisppad-ios/assets/68421539/e7296aff-b4c1-4967-8eec-fc567b4527b9

## Specifications

  - Version: 2.0
  - Platform: iOS 17.3

**Comment by objecthub** [comment]
Wow, this is a pretty serious issue. Thanks for reporting it. It has been fixed with commit 566685e.

**Comment by objecthub** [comment]
This has been fixed with release 2.0.1.
