### ISSUE TITLE
Highlighting applied after loading from command history

### ISSUE THREAD

**Issue by bcg2718** [objecthub/swift-lisppad-ios#4]
## Expected Behavior
Highlighting should only apply temporarily to parentheses

## Actual Behavior
In Console, loading a command from history that begins with parentheses turns on highlighting for newly typed text until the cursor passes over some matching parentheses.

## Steps to Reproduce the Problem

  1. In Console long press the pencil icon on the command input line to bring up the history window
  2. Select a command that is enclosed in parentheses, such as (* 1 1)
  3. After the command has loaded onto the command input line, the cursor will be at the start of the input line. Start typing some text that does not include parentheses and without moving your cursor over any parentheses
  4. Notice the new text is highlighted
  5. Submit the command
  6. Start typing new text
  7. Notice the highlighting remains until matching parentheses are typed

https://github.com/objecthub/swift-lisppad-ios/assets/68421539/353aef2c-13c5-4775-bf76-d2ddb7896f63

## Specifications

  - Version: 2.0
  - Platform: iOS 17.3

**Comment by objecthub** [comment]
Thanks for reporting this bug. Commit 8339ab5 fixes this issue.

**Comment by objecthub** [comment]
This has been fixed with release 2.0.1.
