### ISSUE TITLE
Dragging up on command history acts like dragging an image

### ISSUE THREAD

**Issue by bcg2718** [objecthub/swift-lisppad-ios#5]
## Expected Behavior
In Console, dragging up on the command history list should scroll the list.

## Actual Behavior
The first attempt at dragging up fails and briefly shows a semi-transparent image of the list moving upwards, similar to dragging and dropping an image. The next attempt at dragging works as expected.

## Steps to Reproduce the Problem

  
  1. Load the app
  2. In Console, long press the pencil icon at the end of the command input line to bring up the command history
  3. Drag up on the command history list
  4. Notice the faint image of the command history list that briefly moves upwards and that the command history list itself does not move
  5. Try dragging again and notice the command history list now moves as expected
  6. To repeat the issue, switch to Editor and back to Console and repeat from Step 2
 
 

https://github.com/objecthub/swift-lisppad-ios/assets/68421539/f2c2741b-7de4-4952-bd2e-0bb2bf143742

## Specifications

  - Version: 2.0
  - Platform: iOS 17.3

**Comment by objecthub** [comment]
Thanks for bringing this up. I actually don't have any influence on the animation and rendering of context menus, but the user flow is very disruptive no matter what. I will replace this with a normal menu which is opened on long click only. This should make the whole experience more smoothly and will avoid all the issues you documented.

**Comment by objecthub** [comment]
This was fixed with commit de048a8 . Will close this issue once a new build has been released.

**Comment by objecthub** [comment]
This has been fixed with release 2.0.1.
