### ISSUE TITLE
Matching parentheses highlighting applies to comments and literals

### ISSUE THREAD

**Issue by bcg2718** [objecthub/swift-lisppad-ios#6]
## Expected Behavior
Matching parentheses highlighting should not apply to parentheses in comments and literals, especially when one of the parentheses is a comment or literal and the other is regular code.

## Actual Behavior
Highlighting applies to all parentheses including comments and literals.

## Steps to Reproduce the Problem

  1. In Console or Editor, type
  ```
        (define a
           ; (
           1)
```
2. Notice the final parentheses matches the one in the comment
3. In Console or Editor, type `(define a “(“)`
4. Notice the final parentheses matches the one in the literal

## Specifications

  - Version: 2.0
  - Platform: iOS 17.3

**Comment by objecthub** [comment]
Thanks for your bug report. With commit 95898da I implemented a few heuristics to improve parenthesis matching for Lisp code.

**Comment by objecthub** [comment]
This has been implemented with release 2.0.1.
