### ISSUE TITLE
Highlighting applies to Editor text after opening file

### ISSUE THREAD

**Issue by bcg2718** [objecthub/swift-lisppad-ios#7]
## Expected Behavior
Highlighting should only apply temporarily to matching parentheses

## Actual Behavior
Highlighting applies to all new text in Editor after opening a file whose contents are contained within a single pair of parentheses (the first character is a parentheses and it matches with the last parentheses in the file) unless cursor passes over a parentheses

## Steps to Reproduce the Problem

  1. Switch to Editor
  2. Open a file whose contents are contained within a single pair of parentheses
  3. Without moving the cursor, type some text
  4. Notice it is highlighted
  5. Start a new file
  6. Type some text
  7. Notice it is highlighted

https://github.com/objecthub/swift-lisppad-ios/assets/68421539/343cd1f6-0c74-4ac9-a2bf-ad41161a04ac

## Specifications

  - Version: 2.0
  - Platform: iOS 17.3

**Comment by objecthub** [comment]
Thanks for the bug report. I verified that also this issue is fixed with commit 566685e.

**Comment by objecthub** [comment]
This has been fixed with release 2.0.1.
