### ISSUE TITLE
list evaluation behaves weirdly

### ISSUE THREAD

**Issue by ticolensic** [objecthub/swift-lisppad-ios#8]
On IOS (Ipad), if I run
`(display (cdr (list 1 2 3 4)))`
I expect to have `(1 2 3)`. 

LispPad says
```
[eval error] cannot apply arguments to (1 2 3 4)
> (cdr (1 2 3 4)) <- (<repl> ...)
```

Racket in both sicp and vanilla syntax works no problem. I noticed other situations where `cons` and `list` behave differently. Even though the mechanics behind them is different, my understanding is that the behaviour should be the same (but maybe it's just me).

This may have to go to LispKit, but I don't have MacOS to test it.

P.S. It's a great app to study SICP on the go! So using it, thanks!

**Comment by objecthub** [comment]
I am unable to reproduce this. It appears that you are executing this line of code in a context where `cdr` is defined differently.

When I start up LispPad Go on my iPhone, this is what I get:

```scheme
> (display (cdr (list 1 2 3 4)))
(2 3 4)
```

![IMG_2670](https://github.com/objecthub/swift-lisppad-ios/assets/6752200/1bf3554a-ea21-4faa-97e7-0f6decd51aa0)

**Comment by ticolensic** [comment]
Hi, I must have defined the library functions somewhere, when doing SICP. Closing.
