### ISSUE TITLE
[Feature request] Add 'duplicate line' and 'duplicate selection' menu

### ISSUE THREAD

**Issue by ticolensic** [objecthub/swift-lisppad-ios#9]
When a menu is opened without any selection, show 'duplicate line'.
If a menu is opened on a selection, show 'duplicate selection'.

**Comment by objecthub** [comment]
Thanks for the feature request. I don't fully understand what "Duplicate selection" would do? Would it insert the selected text right after the selection, or would it create a new line with the content of the selection? Would the originally selected text be unselected after the completion of the operation?

**Comment by ticolensic** [comment]
Let's just copy the VSCode behaviour: duplicate the lines that in the selection below the last line of the selection.

I guess, it should be called differently then (e.g. "duplicate line(s)"), to avoid the confusion.

Regarding the unselecting the text, my intuition says, the new lines (that appeared below) should be selected, but up to you.

**Comment by objecthub** [comment]
I've implemented new editing features, including "Duplicate Lines" (and "Delete Lines") matching the behavior of BBEdit (I believe that it matches the VSCode behavior based on your description) with commit ca6b239. I decided against supporting "Duplicate Selection" explicitly given that it's easy to do this via Copy/Paste.

**Comment by objecthub** [comment]
This has been implemented with release 2.0.1.
